### PR TITLE
Pull request assignment 7 programming

### PR DESCRIPTION
**Pull request by IlseBarf**
The debug_input branch on the fork was merged with the master branch on the fork first, since the debug_input was the one that we worked on.

### CODE REVIEW

**Comment by MarjoleinSpijkerman** [comment]
First of all, your code works really well, and it looks really good. 
-	The README is very detailed and explains everything that you would expect the README to contain. 
-	The comments in the code, were clear and concise. 
-	Great instructions on how to run the code on both windows and Linux, making it easy for both experienced and inexperienced coders to run your program

Some possible improvements for the code/functionality:
-	It was mentioned in the README, that the performance of the program depends on the accent. It recognized almost all inputs perfectly, except for the case of “log”, it kept recognizing the word “lock” instead. Maybe you could some cases like this, that the program would also recognize “lock” as log. Maybe you could use something like the Levenshtein distance (edit distance), to calculate for unknown words whether they are still close to some of the possible inputs. 
-	When I tried to say (5*2) * (5*2) this did not work, I tried this twice. It gave the same incorrect solution in both cases, namely “You said open 5 x 2 close x open 5 x 2 +”. It does accept, (5*2) * 4. So, I wonder if it gets stuck on the double use of brackets.
-	You mentioned that this would be the case in the README, that after saying a sentence correctly once that it might get stuck and that it would not accept further sentences. Maybe you could add a case that when it has not received any input for a specific amount of time, that it automatically closes the program. 
-	This is not really an improvement per se, but some of the text in the code is a bit informal. Like the “You said doe maar stop” stop message, which may be confusing for non-Dutch speaking people. Or the extra “what” in “"What? What did you say? Could you repeat it more clearly?" is a bit redundant. However, I understand why just added this the way you did it, as it makes it more fun. 


Some possible improvements for the README
-	This sentence in the readme could be reworded to be a little clearer: "Another challenge was that the recogniser gave the impression of being consistent in the text that it would convert the commands into, but we found out that this would differ between sessions." It's a very interesting problem, and I understand what you are saying, but perhaps re-word the sentence to be more concise for clear reading.

**Comment by IlseBarf** [comment]
Thanks for the input! We implemented some of your suggestions. We did not implement them all.
We did not implement the edit distance, because that is beyond the scope of this project, and we cannot implement it in time.
We did not need to change anything with regard to your second suggestion about the brackets. It will always print the original input first, so that is what you saw. It does not print the tidy equation if the equation is impossible. This was the case in your example, because of the '+' at the end, not because of the brackets.
With regard to your third suggestion, we explained in the readme that we did not implement this, and that this could be done in further extensions. We therefore considered this to be outside the scope of this project.
The informal language is something we implemented on purpose, so we would love to keep this in if you'd agree.

**Comment by MarjoleinSpijkerman** [comment]
> Thanks for the input! We implemented some of your suggestions. We did not implement them all. We did not implement the edit distance, because that is beyond the scope of this project, and we cannot implement it in time. We did not need to change anything with regard to your second suggestion about the brackets. It will always print the original input first, so that is what you saw. It does not print the tidy equation if the equation is impossible. This was the case in your example, because of the '+' at the end, not because of the brackets. With regard to your third suggestion, we explained in the readme that we did not implement this, and that this could be done in further extensions. We therefore considered this to be outside the scope of this project. The informal language is something we implemented on purpose, so we would love to keep this in if you'd agree.

Thank you for your quick reply. Thank you for taking into account some of our suggestions. I agree that implementing the edit distance is outside of the scope of the project, I mainly mentioned it as it could have been an interesting extension. 
With regards to the informal language that was used, I agree that it is a lot more fun than just using basic phrases. So I'd say keep it in!

**Comment by IlseBarf** [comment]
@phat-vtcf
We would suggest a 9 as a grade for our reviewers. The comments really showed that they did try out different things in the code, and also suggested some really interesting solutions, which we regrettably could not implement given the amount of time left. Also, some of the comments were about things we had already covered in the README, but overall it was really good.

**Pull request merged**
